# Site settings
title_left    : "Soobin"
title_right   : "space" # default: ""
description   : "이수빈의 러닝타임"
keywords      : "이수빈, 지똥이, 수똥이, 딥러닝, 머신러닝"
url           : https://log0629.github.io/ # site url
baseurl       : ""
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-XXXXX-XX
twitter_username  : ""
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Soobin Lee"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
